apis/urls.py
from django.urls import path, re_path
from django.conf.urls import url, include
from apis import views as apis_views
from apis import email_reader

app_name="apis"

urlpatterns = [
        path('', apis_views.first_view, name="first_view"),
        url(r'^get_emails/', email_reader.getEmails, name="get_emails"),

    ]

log_viewer/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import django

from .views import (log_json, log_viewer, log_download)

app_name = 'log_viewer'

if django.VERSION >= (2, 0):
    from django.urls import re_path
    urlpatterns = [
        re_path(r'^json/(?P<file_name>[\.\w-]*)/(?P<page>[0-9]+)$', log_json, name='log_json_view'),
        re_path(r'^json/(?P<file_name>[\.\w-]*)$', log_json, name='log_json_view'),
        re_path(r'^download/single-file/$', log_download, name='log_download_file_view'),
        re_path(r'^download.zip$', log_download, name='log_download_zip_view'),
        re_path(r'^$', log_viewer, name='log_file_view'),
    ]
else:
    from django.conf.urls import url
    urlpatterns = [
        url(r'^json/(?P<file_name>[\.\w-]*)/(?P<page>[0-9]+)$', log_json, name='log_json_view'),
        url(r'^json/(?P<file_name>[\.\w-]*)$', log_json, name='log_json_view'),
        url(r'^download/single-file/$', log_download, name='log_download_file_view'),
        url(r'^download.zip$', log_download, name='log_download_zip_view'),
        url(r'^$', log_viewer, name='log_file_view'),
    ]

mail_reader/urls.py
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _
from django.urls import path
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = i18n_patterns(
    url('admin/', admin.site.urls),
    url('', include('apis.urls', namespace='apis')),
    url('logs/', include('log_viewer.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Debug Toolbar If DEBUG TRUE in Settings.py
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

# Change admin site title
admin.site.site_header = 'Mail reader admin'
admin.site.site_title = 'Mail reader admin'
admin.site.index_title = 'Mail reader Administration'

log_viewer/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os
import zipfile
from io import BytesIO
from itertools import islice

from django.http import HttpResponse, Http404
from django.views.generic import TemplateView as _TemplateView
from django.contrib.auth.decorators import (login_required, user_passes_test)
from django.contrib.admin.utils import (quote, unquote)
from django.utils.decorators import method_decorator
from django.utils.functional import SimpleLazyObject
from django.utils.timezone import localtime, now
from django.conf import settings as django_settings
from log_viewer import settings
from log_viewer.utils import (get_log_files, readlines_reverse, JSONResponseMixin)


class TemplateView(_TemplateView):

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(TemplateView, self).dispatch(*args, **kwargs)


class LogJsonView(JSONResponseMixin, TemplateView):

    def get_log_json(self, original_context={}):
        context = {}
        page = original_context.get('page', 1)
        file_name = original_context.get('file_name', '')

        # Clean the `file_name` to avoid relative paths.
        file_name = unquote(file_name).replace('/..', '').replace('..', '')
        page = int(page)
        current_file = file_name

        lines_per_page = settings.LOG_VIEWER_MAX_READ_LINES
        context['original_file_name'] = file_name
        context['next_page'] = page + 1
        context['log_files'] = []

        log_file_data = get_log_files(settings.LOG_VIEWER_FILES_DIR)
        for log_dir, log_files in log_file_data.items():
            for log_file in log_files:
                display = os.path.join(log_dir, log_file)
                uri = os.path.join(settings.LOG_VIEWER_FILES_DIR, display)

                context['log_files'].append({
                    quote(display): {
                        'uri': uri,
                        'display': display,
                    }
                })

        if file_name:
            try:
                file_log = os.path.join(settings.LOG_VIEWER_FILES_DIR, file_name)
                with open(file_log, encoding='utf8', errors='ignore') as file:
                    next_lines = list(islice(readlines_reverse(file, exclude='Not Found'),
                                             (page - 1) * lines_per_page,
                                             page * lines_per_page))
                    data_new_line_list = []
                    
                    for i in next_lines:
                        data_split = i.split('.')
                        
                    for i in data_split:
                        data_join = i+'\n'
                        data_new_line_list.append(data_join)
                        
                    if len(data_new_line_list) < lines_per_page:
                        context['last'] = True
                    else:
                        context['last'] = False
                    context['logs'] = data_new_line_list
                    context['current_file'] = current_file
                    context['file'] = file

            except Exception as error:
                print(error)
                pass
        else:
            context['last'] = True

        if len(context['log_files']) > 0:
            context['log_files'] = sorted(context['log_files'],
                                          key=lambda x: sorted(x.items()))

        return context

    def render_to_response(self, context, **response_kwargs):

        # to support Django 3.1.* (fixed issue #6)
        file_name = context.get('file_name')
        if isinstance(file_name, SimpleLazyObject):
            context = context['view'].kwargs

        log_json = self.get_log_json(context)

        if 'file' in log_json:
            log_json['file'] = log_json['file'].name

        if 'view' in context:
            del context['view']

        context.update(**log_json)
        return self.render_to_json_response(context, **response_kwargs)


class LogDownloadView(TemplateView):

    def render_to_response(self, context, **response_kwargs):
        # file_name = context.get('file_name', None)
        file_name = self.request.GET.get('file_name', None)
        log_file_result = get_log_files(settings.LOG_VIEWER_FILES_DIR)

        if file_name:
            file_path = unquote(file_name)
            uri = os.path.join(settings.LOG_VIEWER_FILES_DIR, file_path)

            log_dir = os.path.dirname(file_path)
            log_file = os.path.basename(file_path)

            if log_file in log_file_result.get(log_dir, []):
                with open(uri, 'rb') as f:
                    buffer = f.read()
                resp = HttpResponse(buffer, content_type='plain/text')
                resp['Content-Disposition'] = 'attachment; filename=%s' % file_name
                return resp
            else:
                raise Http404

        else:
            generation_time = localtime() if django_settings.USE_TZ else now()
            zip_filename = 'log_%s.zip' % generation_time.strftime("%Y%m%dT%H%M%S")
            zip_buffer = BytesIO()

            with zipfile.ZipFile(zip_buffer, 'a', zipfile.ZIP_DEFLATED, False) as zip_file:
                for log_dir, log_files in log_file_result.items():
                    for log_file in log_files:
                        display = os.path.join(log_dir, log_file)
                        uri = os.path.join(settings.LOG_VIEWER_FILES_DIR, display)

                        with open(uri, 'r') as f:
                            zip_file.writestr('%s' % display, f.read())

            zip_buffer.seek(0)
            resp = HttpResponse(zip_buffer, content_type='application/zip')
            resp['Content-Disposition'] = 'attachment; filename=%s' % zip_filename
            return resp


class LogViewerView(TemplateView):
    """
    LogViewerView class

    :cvar template_name: Name of the HTML template used to render the log files

    """
    template_name = "log_viewer/logfile_viewer.html"

    def get_context_data(self, file_name=None, page=1, **kwargs):
        """
        Read and return log files to be showed in admin page

        :param file_name: log file name
        :param page: log viewer page
        """
        context = super(LogViewerView, self).get_context_data(**kwargs)
        context['custom_file_list_title'] = settings.LOG_VIEWER_FILE_LIST_TITLE
        context['custom_style_file'] = settings.LOG_VIEWER_FILE_LIST_STYLES
        context['page_length'] = settings.LOG_VIEWER_PAGE_LENGTH
        return context


log_json = LogJsonView.as_view()
log_viewer = LogViewerView.as_view()
log_download = LogDownloadView.as_view()

templates/log_viewer/logfile_viewer.html
{% extends "admin/base_site.html" %}
{% load static i18n %}
{% block title %}{% trans "Mail reader Log" %}{% endblock %}

{% block breadcrumbs %}
  <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
    &rsaquo;
    <a href="{% url 'log_viewer:log_file_view' %}">{% if custom_file_list_title %}{{ custom_file_list_title }}{% else %}{% trans "Django Log Viewer" %}{% endif %}</a>
  </div>
{% endblock %}

{% block extrastyle %}
  <link rel="stylesheet" type="text/css" href="{% static 'admin/css/changelists.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'log_viewer/css/jquery.dataTables.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'log_viewer/css/log-viewer.css' %}">

  {% if custom_style_file %}
    <link type="text/css" href="{{ custom_style_file }}" rel="stylesheet">
  {% endif %}
{% endblock %}

{% block extrahead %}
  <script src="{% static 'log_viewer/js/jquery.min.js' %}"></script>
  <script src="{% static 'log_viewer/js/jquery.dataTables.min.js' %}"></script>
{% endblock %}

{% block content %}
  <div class="django__log__viewer ">
    <div id="content-main">
      <div class="module filtered" id="changelist">
        <form id="changelist-form" class="changelist-form-container">
          <div class="results">
            <div class="headers">
              <h1 class="pull-left">{% if custom_file_list_title %}{{ custom_file_list_title }}{% else %}{% trans "Django Log Viewer" %}{% endif %}</h1>
              <div class="download-buttons">
                <a href="{% url 'log_viewer:log_download_zip_view' %}" class="btn-download pull-right">{% trans "Download all Log Files" %}</a>
                <a href="{% url 'log_viewer:log_download_file_view' %}" class="btn-download pull-right btn-download-this-log" style="display:none">{% trans "Download this Log File" %}</a>
              </div>
            </div>
            <table id="log-entries" class="display" style="width:100%">
              <thead>
                <tr>
                  <th scope="col">{% trans 'No.' %}</th>
                  <th scope="col">{% trans 'Log entries' %}</th>
                </tr>
              </thead>
              <tbody>
                <tr><td colspan="2">{% trans 'No entries!' %}</td></tr>
              </tbody>
            </table>
          </div>
        </form>
        <div id="changelist-filter">
          <h2>{% trans 'Log Files' %}</h2>
          <div id="log-files-list">
          </div>
        </div>
      </div>
    </div>
  </div>

  <script>
    var entityMap = {
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#39;',
      '/': '&#x2F;',
      '`': '&#x60;',
      '=': '&#x3D;'
    };
    function escapeHtml (string) {
      return String(string).replace(/[&<>"'`=\/]/g, function fromEntityMap (s) {
        return entityMap[s];
      });
    }

    function loadDataTable(table_name, url_json) {
      $(table_name).DataTable({
        pageLength: {{ page_length }},
        columns: [{data: 0}, {data: 1}],
        ajax: function (data, callback, settings) {
          $.ajax({
            type: 'get',
            url: url_json,
            success:function(response){
                const new_logs = [];
                var next_page = response.next_page || 1;

                response.logs.forEach(function(text, numb, logs){
                  text = escapeHtml(text);
                  new_logs.push([numb+1, text]);
                });

                callback({
                  data: new_logs,
                  recordsTotal: next_page,
                  recordsFiltered: next_page
                });
            }
          });
        }
      });
    }

    function loadDataTableTrigger(url_json) {
      var table_name ='table#log-entries';
      if (!$.fn.dataTable.isDataTable(table_name)) {
        loadDataTable(table_name, url_json);
      }else {
        table_dt = $(table_name).DataTable();
        table_dt.destroy();
        loadDataTable(table_name, url_json);
      }
    }

    $(document).ready(function() {
        // just blank entry to get the `log_files`
        var url_json = "{% url 'log_viewer:log_json_view' xxxxx %}";
        $.getJSON(url_json, function(result){
            result.log_files.forEach(function(log) {
                const keys = Object.keys(log);
                Object.entries(log).forEach(([file_name, xtra]) => {
                    // console.log(file_name);
                    // console.log(xtra);
                    var html = '<ul><li><a class="btn-load-json-log" href="javascript:;" '+
                               'data-file-name="'+file_name+'" '+
                               'data-href="'+url_json+file_name+'">'+xtra.display+'</a></li></ul>'
                    $('div#log-files-list').append(html);
                });
            });
        });
    });

    $(document).on('click', '.btn-load-json-log', function(){
        // console.log(this);
        $(this).closest('#log-files-list').find('li').removeClass('selected');
        $(this).closest('li').addClass('selected');
        loadDataTableTrigger($(this).data('href'));

        let btnDownloadSingleFile = $('.btn-download-this-log');
        let file_name = $(this).data('file-name');
        var href = btnDownloadSingleFile.attr('href');

        if(href.indexOf('file_name') > -1) {
          href = href.replace(/\bfile_name=(.*)\b/, 'file_name=' + file_name)
        }else {
          href = href + '?file_name='+ file_name
        }

        btnDownloadSingleFile.attr('href', href);
        btnDownloadSingleFile.show();
    });
  </script>
{% endblock%}